In [2]:
import numpy as np

In [3]:
from itertools import combinations

In [4]:
def update_velocity(moons):
    p = moons[:, :3]
    v = moons[:, 3:]
    pairs = list(combinations(range(moons.shape[0]), 2))
    for i,j in pairs:
        signs = np.sign(p[i, :] - p[j, :])
        v[i, :] -= signs
        v[j, :] += signs

In [5]:
def update_positions(moons):
    p = moons[:, :3]
    v = moons[:, 3:]
    p += v

In [6]:
def calcualte_total_energy(moons):
    p = moons[:, :3]
    v = moons[:, 3:]
    PE = np.sum(np.abs(p), axis=1)
    print(PE)
    KE = np.sum(np.abs(v), axis=1)
    print(KE)
    return np.sum(PE * KE)

In [17]:
%%time
# Initial conditions
total_steps = int(1e6)
moons = [[-1, 0, 2, 0, 0, 0],
         [2, -10, -7, 0, 0, 0],
         [4, -8, 8, 0, 0, 0],
         [3, 5, -1, 0, 0, 0]]
# moons = [[-8, -10, 0, 0, 0, 0],
#          [5, 5, 10, 0, 0, 0],
#          [2, -7, 3, 0, 0, 0],
#          [9, -8, -3, 0, 0, 0]]
# moons = [[-10, -10, -13, 0, 0, 0],
#          [5, 5, -9, 0, 0, 0],
#          [3, 8, -16, 0, 0, 0],
#          [1, 3, -3, 0, 0, 0]]

moons = np.asarray(moons)
x_moons = moons[:, [0, 3]]
y_moons = moons[:, [1, 4]]
z_moons = moons[:, [2, 5]]

for step_no in range(total_steps):
    update_velocity(moons)
    update_positions(moons)
#     print('step_no: ', step_no)
#     display(moons)
#     print('----')
print(moons)
calcualte_total_energy(moons)

[[ 2  2  4 -3  4  3]
 [ 1 -7  5 -1 -3  1]
 [ 3 -9 -4  3 -2 -1]
 [ 2  1 -3  1  1 -3]]
[ 8 13 16  6]
[10  5  6  5]
CPU times: user 26.2 s, sys: 38.9 ms, total: 26.2 s
Wall time: 26.2 s


271

In [ ]:
## Part 2 - how many steps til we get a repeat? (hint: > 1 trillion)

In [32]:
def axis_update_velocity(moons):
    p = moons[:, 0]
    v = moons[:, 1]
    pairs = list(combinations(range(moons.shape[0]), 2))
    for i,j in pairs:
        signs = np.sign(p[i] - p[j])
        v[i] -= signs
        v[j] += signs

In [33]:
def axis_update_positions(moons):
    p = moons[:, 0]
    v = moons[:, 1]
    p += v

In [56]:
def check_single_axis(x_moons):
    previous_x_steps = {}
    i = -1
    while True:
        i += 1
        if np.array_str(x_moons) in previous_x_steps:
            break
        previous_x_steps[np.array_str(x_moons)] = i
        axis_update_velocity(x_moons)
        axis_update_positions(x_moons)
    return i, previous_x_steps[np.array_str(x_moons)]

In [62]:
# moons = [[-1, 0, 2, 0, 0, 0],
#          [2, -10, -7, 0, 0, 0],
#          [4, -8, 8, 0, 0, 0],
#          [3, 5, -1, 0, 0, 0]]
# moons = [[-8, -10, 0, 0, 0, 0],
#          [5, 5, 10, 0, 0, 0],
#          [2, -7, 3, 0, 0, 0],
#          [9, -8, -3, 0, 0, 0]]
moons = [[-10, -10, -13, 0, 0, 0],
         [5, 5, -9, 0, 0, 0],
         [3, 8, -16, 0, 0, 0],
         [1, 3, -3, 0, 0, 0]]

moons = np.asarray(moons)
x_moons = moons[:, [0, 3]]
y_moons = moons[:, [1, 4]]
z_moons = moons[:, [2, 5]]

xi = check_single_axis(x_moons)
yi = check_single_axis(y_moons)
zi = check_single_axis(z_moons)
print(xi, yi, zi)

(167624, 0) (231614, 0) (102356, 0)


In [63]:
np.lcm.reduce([167624, 231614, 102356])

496734501382552